apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-app-secret
  namespace: demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: demo-store
    kind: SecretStore

  target:
    name: demo-app-secret
    creationPolicy: Owner

  data:
  - secretKey: password
    remoteRef:
      key: demo
      property: password