apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: demo-store
  namespace: demo
spec:
  provider:
    kubernetes:
      remoteNamespace: demo
      server:
        url: https://kubernetes.default.svc
      auth:
        serviceAccount:
          name: default