apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: demo-store
  namespace: demo

spec:
  provider:
    kubernetes:
      remoteNamespace: demo
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: demo

      auth:
        serviceAccount:
          name: external-secrets